# Numpy module

installation:

```bash
uv add numpy
or
pip install numpy
```

usage

```py
import numpy as np
```

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

list vs array

list: a python object combined both linked-list and array for dynamic type (like vector for C but dynamic type)

mean: can change the number of element in array, each element can have different data type

array: fixed-size, every element have the same datatype



In [2]:
!uv sync

Resolved 111 packages in 2ms
Audited 107 packages in 0.08ms


In [3]:
import numpy as np

In [4]:
# python-list
arr = [1, "2", 3.0, bin(4), [1,2]]
print(arr)
# numpy array
# arr = np.ndarray([1, "2", 3.0, bin(4)]) # raise Error
arr = np.array([1,2,3,4])
print(arr)
# sepecific numpy array dtype
arr = np.array([1,2,3,4], dtype=np.float32)
print(arr)

[1, '2', 3.0, '0b100', [1, 2]]
[1 2 3 4]
[1. 2. 3. 4.]


In [5]:
# some way to create numpy array
arr = np.zeros([2, 3])
print("shape:", arr.shape)
print("dim:", len(arr.shape))
print("numpy array with shape 2 x 3 full of 0")
print(arr)

print("-"*50)

arr = np.ones([5])
print("shape:", arr.shape)
print("dim:", len(arr.shape))
print("numpy array with shape 5 full of 1")
print(arr)

print("-"*50)

arr = np.full([2, 2, 2], 4)
print("shape:", arr.shape)
print("dim:", len(arr.shape))
print("numpy array with shape 1 x 2 x 3 full of desire value")
print(arr)

arr = np.random.randn(2, 3)
print("shape:", arr.shape)
print("dim:", len(arr.shape))
print("numpy array with shape 2 x 3 random from normal distribution")
print(arr)

shape: (2, 3)
dim: 2
numpy array with shape 2 x 3 full of 0
[[0. 0. 0.]
 [0. 0. 0.]]
--------------------------------------------------
shape: (5,)
dim: 1
numpy array with shape 5 full of 1
[1. 1. 1. 1. 1.]
--------------------------------------------------
shape: (2, 2, 2)
dim: 3
numpy array with shape 1 x 2 x 3 full of desire value
[[[4 4]
  [4 4]]

 [[4 4]
  [4 4]]]
shape: (2, 3)
dim: 2
numpy array with shape 2 x 3 random from normal distribution
[[-1.56915432 -0.49961416  0.27135141]
 [-1.92910279 -1.35532988 -0.50341026]]


In [6]:
# access element or get item
# 2D
arr = np.random.randn(2, 3)
# normal
print(arr)
print(arr[0][1], "or", arr[0, 1])
print("-"*20)
# special
print("first col:", arr[:, 0])    # get the first column
print("second col:", arr[:, 1])    # get the second column

[[ 0.25783262 -1.04605318  1.27812595]
 [-0.24549871 -0.79093242 -0.63666313]]
-1.0460531847048349 or -1.0460531847048349
--------------------
first col: [ 0.25783262 -0.24549871]
second col: [-1.04605318 -0.79093242]


In [7]:
# +, -, *, / -> element wise operator
A = np.array([[4, 8], [12, 16]])
B = np.full(A.shape, 2)


print("+")
print(A+B)
print("-"*10)
print(A-B)
print("-"*10)
print("*")
print(A*B)
print("-"*10)
print("/")
print(A/B)

+
[[ 6 10]
 [14 18]]
----------
[[ 2  6]
 [10 14]]
----------
*
[[ 8 16]
 [24 32]]
----------
/
[[2. 4.]
 [6. 8.]]


In [8]:
# transpose
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)

print("transpose")
print(arr.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
transpose
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
# matmul (matrix multiplication)
A = np.random.randn(2, 3)
B = np.random.randn(3, 4)

# A (2 x 3) matmul B(3 x 4) -> C (2 x 4)
print(A @ B)

[[ 1.84814017  1.77274521 -1.55693988  0.62059279]
 [-1.61460666  0.27153287  0.94589827 -0.4171335 ]]


In [ ]:
def PSNR(image1: np.ndarray[tuple[int, int, int], np.float32], image2: np.ndarray[tuple[int, int, int], np.float32]):
    pass

In [11]:
from PIL import Image

In [12]:
img1 = np.array(Image.open("../img.jpg"))

In [13]:
img2_20 = img1 + np.random.randint(-20, 20, img1.shape)
img2_20[img2_20<0] = 0
img2_20[img2_20>255] = 255

img2_5 = img1 + np.random.randint(-5, 5, img1.shape)
img2_5[img2_5<0] = 0
img2_5[img2_5>255] = 255

img2_1 = img1 + np.random.randint(-1, 1, img1.shape)
img2_1[img2_1<0] = 0
img2_1[img2_1>255] = 255


PSNR(img1, img2_20), PSNR(img1, img2_5), PSNR(img1, img2_1), PSNR(img1, img1)

/var/folders/9q/4zd9js150w5dxg459jsh9rv80000gn/T/ipykernel_27051/3421985237.py:10: RuntimeWarning: divide by zero encountered in scalar divide
  return 10 * np.log10(numerator/denominator)


(np.float64(5.122845810831764),
 np.float64(11.051934527020473),
 np.float64(17.16234146404545),
 np.float64(inf))

In [ ]:
c1 = (0.01 * 255)**2
c2 = (0.03 * 255)**2

def light(x: np.ndarray[tuple[int, int, int], np.float32], y: np.ndarray[tuple[int, int, int], np.float32]):
    pass

def contrast(x: np.ndarray[tuple[int, int, int], np.float32], y: np.ndarray[tuple[int, int, int], np.float32]):
    pass


def structure(x: np.ndarray[tuple[int, int, int], np.float32], y: np.ndarray[tuple[int, int, int], np.float32]):
    pass

def SSIM(x, y, alpha=1, beta=1, gamma=1):
    pass

In [15]:
SSIM(img1, img2_20), SSIM(img1, img2_5), SSIM(img1, img2_1), SSIM(img1, img1)

(np.float64(0.9999658613370064),
 np.float64(0.9999973001443035),
 np.float64(0.999999403545883),
 np.float64(1.0))